services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.3
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=speedio
      - xpack.security.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - xpack.security.http.ssl.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - backend

  rails:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    depends_on:
      - elasticsearch
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - .:/api
    networks:
      - backend

volumes:
  esdata:
    driver: local

networks:
  backend:
    driver: bridge
