services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.3
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=speedio
      - xpack.security.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - xpack.security.http.ssl.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - backend

  rails:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    depends_on:
      - elasticsearch
      - mongodb
    ports:
      - "3000:3000"
    volumes:
      - .:/api
    networks:
      - backend

  mongodb:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: Companies
    networks:
      - backend

volumes:
  esdata:
    driver: local
  mongo_data:
    driver: local

networks:
  backend:
    driver: bridge
