development:
  clients:
    default:
      database: Companies
      hosts:
        - mongo:27017
      username: root
      password: root
      options:
        retry_writes: true
        auth_source: admin

  options:
    log_level: :error